/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
/**
 *
 * @author Geovanni
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JPanel();
        menuBarInicio = new javax.swing.JMenuBar();
        MenuArchivoInicio = new javax.swing.JMenu();
        itemMenuInicioInicio = new javax.swing.JMenuItem();
        itemMenuSalirInicio = new javax.swing.JMenuItem();
        menuMantenedoresInicio = new javax.swing.JMenu();
        itemMenuProfesionalesInicio = new javax.swing.JMenuItem();
        itemMenuClientesInicio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );

        MenuArchivoInicio.setText("Archivo");

        itemMenuInicioInicio.setText("Inicio");
        itemMenuInicioInicio.setEnabled(false);
        MenuArchivoInicio.add(itemMenuInicioInicio);

        itemMenuSalirInicio.setText("Salir");
        itemMenuSalirInicio.setToolTipText("");
        itemMenuSalirInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSalirInicioActionPerformed(evt);
            }
        });
        MenuArchivoInicio.add(itemMenuSalirInicio);

        menuBarInicio.add(MenuArchivoInicio);

        menuMantenedoresInicio.setText("Mantenedores");

        itemMenuProfesionalesInicio.setText("Profesionales");
        itemMenuProfesionalesInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuProfesionalesInicioActionPerformed(evt);
            }
        });
        menuMantenedoresInicio.add(itemMenuProfesionalesInicio);

        itemMenuClientesInicio.setText("Clientes");
        itemMenuClientesInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuClientesInicioActionPerformed(evt);
            }
        });
        menuMantenedoresInicio.add(itemMenuClientesInicio);

        menuBarInicio.add(menuMantenedoresInicio);

        setJMenuBar(menuBarInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuSalirInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSalirInicioActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemMenuSalirInicioActionPerformed

    private void itemMenuProfesionalesInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuProfesionalesInicioActionPerformed
        MantenedorProfesionales m = new MantenedorProfesionales();
        Controlador c = new Controlador(m);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemMenuProfesionalesInicioActionPerformed

    private void itemMenuClientesInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuClientesInicioActionPerformed
        MantenedorClientes mantenedorClientes = new MantenedorClientes();
        mantenedorClientes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemMenuClientesInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuArchivoInicio;
    private javax.swing.JMenuItem itemMenuClientesInicio;
    private javax.swing.JMenuItem itemMenuInicioInicio;
    private javax.swing.JMenuItem itemMenuProfesionalesInicio;
    private javax.swing.JMenuItem itemMenuSalirInicio;
    private javax.swing.JMenuBar menuBarInicio;
    private javax.swing.JMenu menuMantenedoresInicio;
    private javax.swing.JPanel panelInicio;
    // End of variables declaration//GEN-END:variables
}
