package Vista;

import Controlador.Controlador;

/**
 *
 * @author Geovanni
 */
public class MantenedorProfesionales extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public MantenedorProfesionales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaProfesionales = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivoMantenedorProfesionales = new javax.swing.JMenu();
        itemMenuInicioMantendorProfesional = new javax.swing.JMenuItem();
        itemMenuSalirMantenedorProfesionales = new javax.swing.JMenuItem();
        menuMantenedoresMantenedorProfesional = new javax.swing.JMenu();
        itemMenuProfesionalesMantenedorProfesionales = new javax.swing.JMenuItem();
        itemMenuClientesMantendorProfesionales = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profesionales");
        setPreferredSize(new java.awt.Dimension(1500, 800));

        btnListar.setText("Listar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnListar)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListar)
                .addGap(50, 50, 50))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Profesionales"));

        tablaListaProfesionales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Rut", "Nombre", "Apellido P", "Apellido M", "Direccion", "Telefono", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaListaProfesionales);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1334, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuArchivoMantenedorProfesionales.setText("Archivo");

        itemMenuInicioMantendorProfesional.setText("Inicio");
        itemMenuInicioMantendorProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuInicioMantendorProfesionalActionPerformed(evt);
            }
        });
        menuArchivoMantenedorProfesionales.add(itemMenuInicioMantendorProfesional);

        itemMenuSalirMantenedorProfesionales.setText("Salir");
        itemMenuSalirMantenedorProfesionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSalirMantenedorProfesionalesActionPerformed(evt);
            }
        });
        menuArchivoMantenedorProfesionales.add(itemMenuSalirMantenedorProfesionales);

        jMenuBar1.add(menuArchivoMantenedorProfesionales);

        menuMantenedoresMantenedorProfesional.setText("Mantenedores");

        itemMenuProfesionalesMantenedorProfesionales.setText("Profesionales");
        itemMenuProfesionalesMantenedorProfesionales.setEnabled(false);
        menuMantenedoresMantenedorProfesional.add(itemMenuProfesionalesMantenedorProfesionales);

        itemMenuClientesMantendorProfesionales.setText("Clientes");
        itemMenuClientesMantendorProfesionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuClientesMantendorProfesionalesActionPerformed(evt);
            }
        });
        menuMantenedoresMantenedorProfesional.add(itemMenuClientesMantendorProfesionales);

        jMenuBar1.add(menuMantenedoresMantenedorProfesional);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuSalirMantenedorProfesionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSalirMantenedorProfesionalesActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemMenuSalirMantenedorProfesionalesActionPerformed

    private void itemMenuInicioMantendorProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuInicioMantendorProfesionalActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemMenuInicioMantendorProfesionalActionPerformed

    private void itemMenuClientesMantendorProfesionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuClientesMantendorProfesionalesActionPerformed
        MantenedorClientes mantenedorClientes = new MantenedorClientes();
        mantenedorClientes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemMenuClientesMantendorProfesionalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { //metodo original
//       java.awt.EventQueue.invokeLater(new Runnable(){
//           public void run(){
//               new Inicio().setVisible(true);
//           }
//       });
        
        
        //Metodo que trabaja controlador
        MantenedorProfesionales m=new MantenedorProfesionales();
        Controlador c = new Controlador(m);
        m.setVisible(true);
//        m.setLocationRelativeTo(m);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnListar;
    private javax.swing.JMenuItem itemMenuClientesMantendorProfesionales;
    private javax.swing.JMenuItem itemMenuInicioMantendorProfesional;
    private javax.swing.JMenuItem itemMenuProfesionalesMantenedorProfesionales;
    private javax.swing.JMenuItem itemMenuSalirMantenedorProfesionales;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuArchivoMantenedorProfesionales;
    private javax.swing.JMenu menuMantenedoresMantenedorProfesional;
    public javax.swing.JTable tablaListaProfesionales;
    // End of variables declaration//GEN-END:variables
}
