/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Geovanni
 */
public class MantenedorClientes extends javax.swing.JFrame {

    /**
     * Creates new form MantenedorClientes
     */
    public MantenedorClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivoMantenedorClientes = new javax.swing.JMenu();
        itemMenuInicioMantenedorClientes = new javax.swing.JMenuItem();
        itemMenuSalirMantenedorClientes = new javax.swing.JMenuItem();
        menuMantenedoresMantenedorClientes = new javax.swing.JMenu();
        itemMenuProfesionalesMantenedorClientes = new javax.swing.JMenuItem();
        itemMenuClientesMantenedorClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArchivoMantenedorClientes.setText("Archivo");

        itemMenuInicioMantenedorClientes.setText("Inicio");
        itemMenuInicioMantenedorClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuInicioMantenedorClientesActionPerformed(evt);
            }
        });
        menuArchivoMantenedorClientes.add(itemMenuInicioMantenedorClientes);

        itemMenuSalirMantenedorClientes.setText("Salir");
        itemMenuSalirMantenedorClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSalirMantenedorClientesActionPerformed(evt);
            }
        });
        menuArchivoMantenedorClientes.add(itemMenuSalirMantenedorClientes);

        jMenuBar1.add(menuArchivoMantenedorClientes);

        menuMantenedoresMantenedorClientes.setText("Mantenedores");

        itemMenuProfesionalesMantenedorClientes.setText("Profesionales");
        itemMenuProfesionalesMantenedorClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuProfesionalesMantenedorClientesActionPerformed(evt);
            }
        });
        menuMantenedoresMantenedorClientes.add(itemMenuProfesionalesMantenedorClientes);

        itemMenuClientesMantenedorClientes.setText("Clientes");
        itemMenuClientesMantenedorClientes.setEnabled(false);
        menuMantenedoresMantenedorClientes.add(itemMenuClientesMantenedorClientes);

        jMenuBar1.add(menuMantenedoresMantenedorClientes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuSalirMantenedorClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSalirMantenedorClientesActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemMenuSalirMantenedorClientesActionPerformed

    private void itemMenuInicioMantenedorClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuInicioMantenedorClientesActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemMenuInicioMantenedorClientesActionPerformed

    private void itemMenuProfesionalesMantenedorClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuProfesionalesMantenedorClientesActionPerformed
        MantenedorProfesionales mantenedoresProfesionales = new MantenedorProfesionales();
        mantenedoresProfesionales.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemMenuProfesionalesMantenedorClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMenuClientesMantenedorClientes;
    private javax.swing.JMenuItem itemMenuInicioMantenedorClientes;
    private javax.swing.JMenuItem itemMenuProfesionalesMantenedorClientes;
    private javax.swing.JMenuItem itemMenuSalirMantenedorClientes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuArchivoMantenedorClientes;
    private javax.swing.JMenu menuMantenedoresMantenedorClientes;
    // End of variables declaration//GEN-END:variables
}
